version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    environment:
      - REDIS_PORT=6379
      - NODE_ENV=development
      - PORT=3000
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"